console.log('Math.floor(Math.PI * 100) / 100:', Math.floor(Math.PI * 100) / 100)
console.log('Math.imul(3, 2):', Math.imul(3, 2))
console.log('Math.pow(2, 10):', Math.pow(2, 10))
console.log('Math.log(Math.E):', Math.log(Math.E))
console.log('Math.ceil(Math.LOG10E):', Math.ceil(Math.LOG10E))
console.log('Math.sin(90):', Math.sin(90))
console.log('Math.sqrt(4):', Math.sqrt(4))
console.log('Math.tan(45):', Math.tan(45))
console.log('Math.trunc(2.000001):', Math.trunc(2.000001))
console.log('Math.max(1):', Math.max(1))
console.log('Math.max(1, 2):', Math.max(1, 2))
console.log('Math.max(1, 2, -1):', Math.max(1, 2, -1))
console.log('Math.max(1):', Math.max(1))
console.log('Math.max(1, 2):', Math.max(1, 2))
console.log('Math.max(1, 2, -1):', Math.max(1, 2, -1))
console.log('Math.random() != Math.random()', Math.random() != Math.random())
console.log('Math.random() <= 1 && Math.random() >= 0', Math.random() <= 1 && Math.random() >= 0)
console.log('NaN', NaN)
console.log('isNaN(NaN)', isNaN(NaN))
